name: PF Workflow
on: [ push ]
env:
  SERVICE_NAME: plush-forest-web
  COMPOSE_FILE: /home/docker-compose.yml
  DEVELOPMENT_BRANCH_REF: refs/heads/master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Webpack Build & Checks
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      # Build & Publish a Docker Image | Master Branch Only
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Downcase Repo Name for Registry
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/${{ env.SERVICE_NAME }}:latest
  DeployDev:
    runs-on: ubuntu-latest
    needs: [ Build ]
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      CLIENT_API_URL: https://api.plush.dev
      CLIENT_PLAI_CONTRACT_ADDRESS: "0x6FB60c408363636dAC206AA98EE429d79923DD33"
      CLIENT_PLUSH_CONTRACT_ADDRESS: "0x6FB60c408363636dAC206AA98EE429d79923DD33"
      CLIENT_CORE_CONTRACT_ADDRESS: "0x8b25Bff08FDF1e1dCBA755C7BeECA6Ff233D5998"
      CLIENT_TREE_CONTRACT_ADDRESS: "0x6c530C2A97e1Fa224Be020f53f1Cbcc0DB001C01"
      CLIENT_FOREST_CONTRACT_ADDRESS: "0xeAbc3d08AC7E09e432bc61c040E9B121A010226E"
      CLIENT_COIN_WALLETS_CONTRACT_ADDRESS: "0x77B02dc3dcE4D20E60bb83DEa44934026634dF04"
      CLIENT_NETWORK_ID: "80001"
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: newbly.com
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY_FOR_DEPLOY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE_FOR_DEPLOY }}
          envs: COMPOSE_FILE, SERVICE_NAME, CLIENT_API_URL, CLIENT_PLAI_CONTRACT_ADDRESS, CLIENT_PLUSH_CONTRACT_ADDRESS, CLIENT_CORE_CONTRACT_ADDRESS, CLIENT_TREE_CONTRACT_ADDRESS, CLIENT_NETWORK_ID, CLIENT_FOREST_CONTRACT_ADDRESS, CLIENT_COIN_WALLETS_CONTRACT_ADDRESS
          script: |
            export CLIENT_API_URL=$CLIENT_API_URL
            export CLIENT_PLAI_CONTRACT_ADDRESS=$CLIENT_PLAI_CONTRACT_ADDRESS
            export CLIENT_PLUSH_CONTRACT_ADDRESS=$CLIENT_PLUSH_CONTRACT_ADDRESS
            export CLIENT_CORE_CONTRACT_ADDRESS=$CLIENT_CORE_CONTRACT_ADDRESS
            export CLIENT_TREE_CONTRACT_ADDRESS=$CLIENT_TREE_CONTRACT_ADDRESS
            export CLIENT_NETWORK_ID=$CLIENT_NETWORK_ID
            export CLIENT_FOREST_CONTRACT_ADDRESS=$CLIENT_FOREST_CONTRACT_ADDRESS
            export CLIENT_COIN_WALLETS_CONTRACT_ADDRESS=$CLIENT_COIN_WALLETS_CONTRACT_ADDRESS
            docker-compose pull $SERVICE_NAME
            docker-compose up -d --no-deps --build $SERVICE_NAME