name: PF Workflow
on: [ push ]
env:
  SERVICE_NAME: plush-forest-web
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Webpack Build & Checks
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      # Build & Publish a Docker Image | Master Branch Only
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Downcase Repo Name for Registry
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/${{ env.SERVICE_NAME }}:latest
  DeployDev:
    runs-on: ubuntu-latest
    needs: [ Build ]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: PlushFamily/infrastructure
          event-type: deploy-dev
          client-payload: '{"service": "plush-forest"}'
